<table width="100%">
<tr>
<td width="50%" align="left"></td>
<td width="50%" align="right"><a href="./01_RQ1_population_demand.ipynb">Next: RQ1 — Population Demand →</a></td>
</tr>
</table>

## **Data Exploration and Analysis**

In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine
from dotenv import load_dotenv

import os

import matplotlib.pyplot as plt

In [2]:
import pandas as pd
from daytascape_db_core.connection import get_db_engine

In [3]:
DATABASE = "health_system_performance"

engine = get_db_engine(DATABASE)

print("Connected database:", engine.url.database)

Connected database: health_system_performance

In [4]:
query = """
SELECT *
FROM master.analytics_province_year;
"""

df = pd.read_sql(query, engine)

print("Connected successfully to database!")

df.head(10)

Connected successfully to database!

,province_id,province_code,province_name,data_year,population,population_65_plus,population_80_plus,population_85_plus,population_65_share_pct,population_80_share_pct,...,private_health_expenditure_constant_2010_per_capita,provincial_government_health_expenditure_current,provincial_government_health_expenditure_per_capita,provincial_government_health_expenditure_constant_2010,provincial_government_health_expenditure_constant_2010_per_capi,territorial_government_health_expenditure_current,territorial_government_health_expenditure_per_capita,territorial_government_health_expenditure_constant_2010,territorial_government_health_expenditure_constant_2010_per_cap,nurses_total
0,15,PE,Prince Edward Island,2024,179709.0,36849.0,8218.0,3886.0,20.504816,4.572948,...,1914.110532,1.228779e+09,6881.989110,8.254174e+08,4622.892113,NaN,NaN,NaN,NaN,NaN
1,6,AB,Alberta,1975,1808689.0,134156.0,27442.0,12282.0,7.417306,1.517232,...,663.549287,6.949125e+08,384.207843,3.428803e+09,1895.739423,NaN,NaN,NaN,NaN,NaN
2,7,BC,British Columbia,1975,2499564.0,236960.0,51071.0,23239.0,9.480053,2.043196,...,679.794364,9.281825e+08,371.337761,4.379023e+09,1751.914626,NaN,NaN,NaN,NaN,NaN
3,7,BC,British Columbia,2022,5358845.0,1054174.0,250939.0,124925.0,19.671664,4.682707,...,2273.051979,3.010337e+10,5618.936230,2.317900e+10,4326.469070,NaN,NaN,NaN,NaN,108708.0
4,9,NB,New Brunswick,2021,790802.0,178652.0,39837.0,19193.0,22.591243,5.037544,...,2191.698134,3.945472e+09,4989.203072,3.151362e+09,3985.020465,NaN,NaN,NaN,NaN,NaN
5,5,CA,Canada,1975,23143275.0,1957075.0,377982.0,160362.0,8.456344,1.633226,...,568.363206,8.709289e+09,376.320519,4.111742e+10,1776.646681,NaN,NaN,NaN,NaN,NaN
6,8,MB,Manitoba,1975,1024975.0,104215.0,22287.0,9920.0,10.167565,2.174394,...,494.535967,3.766992e+08,367.520427,1.852127e+09,1806.997401,NaN,NaN,NaN,NaN,NaN
7,14,ON,Ontario,1980,8746013.0,850356.0,165961.0,70416.0,9.722785,1.897562,...,776.538159,5.164564e+09,590.505011,1.629120e+10,1862.700006,NaN,NaN,NaN,NaN,NaN
8,16,QC,Quebec,2020,8551095.0,1673371.0,401828.0,204785.0,19.569084,4.699141,...,1755.558556,4.704125e+10,5501.196296,3.642464e+10,4259.646558,NaN,NaN,NaN,NaN,NaN
9,14,ON,Ontario,2016,13876500.0,2260652.0,593482.0,302656.0,16.291226,4.276885,...,2000.807682,5.655294e+10,4075.446981,5.104966e+10,3678.856840,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(730, 81)

In [6]:
df.head()

,province_id,province_code,province_name,data_year,population,population_65_plus,population_80_plus,population_85_plus,population_65_share_pct,population_80_share_pct,...,private_health_expenditure_constant_2010_per_capita,provincial_government_health_expenditure_current,provincial_government_health_expenditure_per_capita,provincial_government_health_expenditure_constant_2010,provincial_government_health_expenditure_constant_2010_per_capi,territorial_government_health_expenditure_current,territorial_government_health_expenditure_per_capita,territorial_government_health_expenditure_constant_2010,territorial_government_health_expenditure_constant_2010_per_cap,nurses_total
0,15,PE,Prince Edward Island,2024,179709.0,36849.0,8218.0,3886.0,20.504816,4.572948,...,1914.110532,1.228779e+09,6881.989110,8.254174e+08,4622.892113,NaN,NaN,NaN,NaN,NaN
1,6,AB,Alberta,1975,1808689.0,134156.0,27442.0,12282.0,7.417306,1.517232,...,663.549287,6.949125e+08,384.207843,3.428803e+09,1895.739423,NaN,NaN,NaN,NaN,NaN
2,7,BC,British Columbia,1975,2499564.0,236960.0,51071.0,23239.0,9.480053,2.043196,...,679.794364,9.281825e+08,371.337761,4.379023e+09,1751.914626,NaN,NaN,NaN,NaN,NaN
3,7,BC,British Columbia,2022,5358845.0,1054174.0,250939.0,124925.0,19.671664,4.682707,...,2273.051979,3.010337e+10,5618.936230,2.317900e+10,4326.469070,NaN,NaN,NaN,NaN,108708.0
4,9,NB,New Brunswick,2021,790802.0,178652.0,39837.0,19193.0,22.591243,5.037544,...,2191.698134,3.945472e+09,4989.203072,3.151362e+09,3985.020465,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail()

,province_id,province_code,province_name,data_year,population,population_65_plus,population_80_plus,population_85_plus,population_65_share_pct,population_80_share_pct,...,private_health_expenditure_constant_2010_per_capita,provincial_government_health_expenditure_current,provincial_government_health_expenditure_per_capita,provincial_government_health_expenditure_constant_2010,provincial_government_health_expenditure_constant_2010_per_capi,territorial_government_health_expenditure_current,territorial_government_health_expenditure_per_capita,territorial_government_health_expenditure_constant_2010,territorial_government_health_expenditure_constant_2010_per_cap,nurses_total
725,17,SK,Saskatchewan,2015,1122210.0,165795.0,49833.0,26856.0,14.773973,4.440613,...,1743.025598,5.364562e+09,4780.355135,4.579779e+09,4081.035951,NaN,NaN,NaN,NaN,28594.0
726,16,QC,Quebec,2019,8483186.0,1622802.0,394550.0,203442.0,19.129629,4.650965,...,1697.938274,3.879926e+10,4573.665578,3.145544e+10,3707.974931,NaN,NaN,NaN,NaN,NaN
727,13,NU,Nunavut,1995,24978.0,533.0,81.0,41.0,2.133878,0.324285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,13,NU,Nunavut,1996,25669.0,559.0,88.0,45.0,2.177724,0.342826,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,13,NU,Nunavut,1997,25884.0,578.0,83.0,41.0,2.233040,0.320661,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns

Index(['province_id', 'province_code', 'province_name', 'data_year',
       'population', 'population_65_plus', 'population_80_plus',
       'population_85_plus', 'population_65_share_pct',
       'population_80_share_pct', 'population_85_share_pct',
       'hospital_beds_total', 'current_hospital_beds_total',
       'physicians_total', 'registered_nurses', 'licensed_practical_nurses',
       'nurse_practitioners', 'registered_psychiatric_nurses', 'icu_beds',
       'long_term_care_beds', 'mental_health_addictions_beds',
       'obstetrics_beds', 'other_acute_care_beds', 'pediatrics_beds',
       'rated_capacity_beds', 'rehabilitation_beds',
       'bladder_cancer_surgery_median',
       'bladder_cancer_surgery_90th_percentile',
       'breast_cancer_surgery_median', 'breast_cancer_surgery_90th_percentile',
       'cabg_median', 'cabg_90th_percentile', 'cataract_surgery_median',
       'cataract_surgery_90th_percentile', 'colorectal_cancer_surgery_median',
       'colorectal_cancer_surgery_90th_percentile', 'ct_scan_median',
       'ct_scan_90th_percentile', 'hip_fracture_repair_median',
       'hip_fracture_repair_90th_percentile',
       'hip_fracture_repair_emergency_inpatient_median',
       'hip_fracture_repair_emergency_inpatient_90th_percentile',
       'hip_replacement_median', 'hip_replacement_90th_percentile',
       'knee_replacement_median', 'knee_replacement_90th_percentile',
       'lung_cancer_surgery_median', 'lung_cancer_surgery_90th_percentile',
       'mri_scan_median', 'mri_scan_90th_percentile',
       'prostate_cancer_surgery_median',
       'prostate_cancer_surgery_90th_percentile', 'radiation_therapy_median',
       'radiation_therapy_90th_percentile', 'joint_replacement_cases',
       'joint_replacement_pct_within_benchmark',
       'hip_fracture_surgery_risk_adjusted_rate',
       'hospital_readmission_risk_adjusted_rate',
       'avoidable_hospitalizations_age_standardized_rate',
       'standardized_hospitalization_rate', 'total_health_expenditure_current',
       'total_health_expenditure_per_capita',
       'total_health_expenditure_constant_2010',
       'total_health_expenditure_constant_2010_per_capita',
       'public_health_expenditure_current',
       'public_health_expenditure_per_capita',
       'public_health_expenditure_constant_2010',
       'public_health_expenditure_constant_2010_per_capita',
       'private_health_expenditure_current',
       'private_health_expenditure_per_capita',
       'private_health_expenditure_constant_2010',
       'private_health_expenditure_constant_2010_per_capita',
       'provincial_government_health_expenditure_current',
       'provincial_government_health_expenditure_per_capita',
       'provincial_government_health_expenditure_constant_2010',
       'provincial_government_health_expenditure_constant_2010_per_capi',
       'territorial_government_health_expenditure_current',
       'territorial_government_health_expenditure_per_capita',
       'territorial_government_health_expenditure_constant_2010',
       'territorial_government_health_expenditure_constant_2010_per_cap',
       'nurses_total'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 81 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   province_id                                                      730 non-null    int64
 1   province_code                                                    730 non-null    str
 2   province_name                                                    730 non-null    str
 3   data_year                                                        730 non-null    int64
 4   population                                                       730 non-null    float64
 5   population_65_plus                                               730 non-null    float64
 6   population_80_plus                                               730 non-null    float64
 7   population_85_plus                                               730 non-null    float64
 8   population_65_share_pct                                          730 non-null    float64
 9   population_80_share_pct                                          730 non-null    float64
 10  population_85_share_pct                                          730 non-null    float64
 11  hospital_beds_total                                              178 non-null    float64
 12  current_hospital_beds_total                                      12 non-null     float64
 13  physicians_total                                                 336 non-null    float64
 14  registered_nurses                                                101 non-null    float64
 15  licensed_practical_nurses                                        109 non-null    float64
 16  nurse_practitioners                                              102 non-null    float64
 17  registered_psychiatric_nurses                                    40 non-null     float64
 18  icu_beds                                                         150 non-null    float64
 19  long_term_care_beds                                              133 non-null    float64
 20  mental_health_addictions_beds                                    146 non-null    float64
 21  obstetrics_beds                                                  147 non-null    float64
 22  other_acute_care_beds                                            160 non-null    float64
 23  pediatrics_beds                                                  146 non-null    float64
 24  rated_capacity_beds                                              67 non-null     float64
 25  rehabilitation_beds                                              146 non-null    float64
 26  bladder_cancer_surgery_median                                    131 non-null    float64
 27  bladder_cancer_surgery_90th_percentile                           131 non-null    float64
 28  breast_cancer_surgery_median                                     142 non-null    float64
 29  breast_cancer_surgery_90th_percentile                            142 non-null    float64
 30  cabg_median                                                      157 non-null    float64
 31  cabg_90th_percentile                                             157 non-null    float64
 32  cataract_surgery_median                                          194 non-null    float64
 33  cataract_surgery_90th_percentile                                 194 non-null    float64
 34  colorectal_cancer_surgery_median                                 131 non-null    float64
 35  colorectal_cancer_surgery_90th_percentile                        131 non-null    float64
 36  ct_scan_median                                                   116 non-null    float64
 37  ct_scan_90th_percentile                                          116 non-null    float64
 38  hip_fracture_repair_median                                       167 non-null    float64
 39  hip_fracture_repair_90th_percentile                              167 non-null    float64
 40  hip_fracture_repair_emergency_inpatient_median                   61 non-null     float64
 41  hip_fracture_repair_emergency_inpatient_90th_percentile          61 non-null     float64
 42  hip_replacement_median                                           194 non-null    float64
 43  hip_replacement_90th_percentile                                  194 non-null    float64
 44  knee_replacement_median                                          194 non-null    float64
 45  knee_replacement_90th_percentile                                 194 non-null    float64
 46  lung_cancer_surgery_median                                       125 non-null    float64
 47  lung_cancer_surgery_90th_percentile                              125 non-null    float64
 48  mri_scan_median                                                  116 non-null    float64
 49  mri_scan_90th_percentile                                         116 non-null    float64
 50  prostate_cancer_surgery_median                                   120 non-null    float64
 51  prostate_cancer_surgery_90th_percentile                          120 non-null    float64
 52  radiation_therapy_median                                         170 non-null    float64
 53  radiation_therapy_90th_percentile                                168 non-null    float64
 54  joint_replacement_cases                                          72 non-null     float64
 55  joint_replacement_pct_within_benchmark                           77 non-null     float64
 56  hip_fracture_surgery_risk_adjusted_rate                          45 non-null     float64
 57  hospital_readmission_risk_adjusted_rate                          63 non-null     float64
 58  avoidable_hospitalizations_age_standardized_rate                 145 non-null    float64
 59  standardized_hospitalization_rate                                402 non-null    float64
 60  total_health_expenditure_current                                 674 non-null    float64
 61  total_health_expenditure_per_capita                              674 non-null    float64
 62  total_health_expenditure_constant_2010                           674 non-null    float64
 63  total_health_expenditure_constant_2010_per_capita                674 non-null    float64
 64  public_health_expenditure_current                                674 non-null    float64
 65  public_health_expenditure_per_capita                             674 non-null    float64
 66  public_health_expenditure_constant_2010                          674 non-null    float64
 67  public_health_expenditure_constant_2010_per_capita               674 non-null    float64
 68  private_health_expenditure_current                               674 non-null    float64
 69  private_health_expenditure_per_capita                            674 non-null    float64
 70  private_health_expenditure_constant_2010                         674 non-null    float64
 71  private_health_expenditure_constant_2010_per_capita              674 non-null    float64
 72  provincial_government_health_expenditure_current                 561 non-null    float64
 73  provincial_government_health_expenditure_per_capita              561 non-null    float64
 74  provincial_government_health_expenditure_constant_2010           561 non-null    float64
 75  provincial_government_health_expenditure_constant_2010_per_capi  561 non-null    float64
 76  territorial_government_health_expenditure_current                113 non-null    float64
 77  territorial_government_health_expenditure_per_capita             113 non-null    float64
 78  territorial_government_health_expenditure_constant_2010          113 non-null    float64
 79  territorial_government_health_expenditure_constant_2010_per_cap  113 non-null    float64
 80  nurses_total                                                     33 non-null     float64
dtypes: float64(77), int64(2), str(2)
memory usage: 462.1 KB

In [10]:
df.dtypes

province_id                                                          int64
province_code                                                          str
province_name                                                          str
data_year                                                            int64
population                                                         float64
                                                                    ...
territorial_government_health_expenditure_current                  float64
territorial_government_health_expenditure_per_capita               float64
territorial_government_health_expenditure_constant_2010            float64
territorial_government_health_expenditure_constant_2010_per_cap    float64
nurses_total                                                       float64
Length: 81, dtype: object

In [11]:
df.describe()

,province_id,data_year,population,population_65_plus,population_80_plus,population_85_plus,population_65_share_pct,population_80_share_pct,population_85_share_pct,hospital_beds_total,...,private_health_expenditure_constant_2010_per_capita,provincial_government_health_expenditure_current,provincial_government_health_expenditure_per_capita,provincial_government_health_expenditure_constant_2010,provincial_government_health_expenditure_constant_2010_per_capi,territorial_government_health_expenditure_current,territorial_government_health_expenditure_per_capita,territorial_government_health_expenditure_constant_2010,territorial_government_health_expenditure_constant_2010_per_cap,nurses_total
count,730.000000,730.000000,7.300000e+02,7.300000e+02,7.300000e+02,730.000000,730.000000,730.000000,730.000000,178.000000,...,674.000000,5.610000e+02,561.000000,5.610000e+02,561.000000,1.130000e+02,113.000000,1.130000e+02,113.000000,33.000000
mean,11.472603,1998.958904,4.582358e+06,6.084462e+05,1.439184e+05,67077.475342,11.864201,2.738507,1.269485,7137.202247,...,1255.853539,1.626805e+10,2706.748731,1.752487e+10,3069.244878,2.774720e+08,6949.850406,2.598165e+08,6597.884390,71334.242424
std,4.134560,15.704261,8.230669e+06,1.194007e+06,2.930624e+05,141302.105540,4.675013,1.318196,0.676280,9259.679899,...,617.836975,3.419610e+10,1832.553962,3.025923e+10,939.056560,2.109516e+08,4934.026795,1.423148e+08,3168.862802,35452.260780
min,5.000000,1971.000000,1.899100e+04,4.320000e+02,5.700000e+01,15.000000,1.887864,0.249093,0.067708,49.000000,...,264.823920,4.150800e+07,300.867937,1.927551e+08,1425.530997,6.171500e+06,281.700749,2.782801e+07,1270.221531,28594.000000
25%,8.000000,1986.000000,5.122542e+05,3.599150e+04,7.295250e+03,3327.500000,9.222521,1.769062,0.738201,488.000000,...,746.836869,1.228779e+09,1233.451014,2.136289e+09,2319.924591,1.038470e+08,3213.429849,1.305288e+08,4302.342349,31566.000000
50%,11.500000,1999.000000,1.005448e+06,1.439500e+05,3.458550e+04,16144.000000,12.188560,2.677717,1.179915,3127.000000,...,1106.592716,3.904789e+09,2083.389863,4.579779e+09,2892.216963,2.245636e+08,5908.400505,2.815050e+08,6008.302511,95948.000000
75%,15.000000,2012.000000,4.510503e+06,5.727842e+05,1.270595e+05,55835.000000,14.561448,3.969603,1.868794,11041.250000,...,1720.562292,1.507927e+10,4190.412343,1.801105e+10,3840.662992,4.119098e+08,10100.839819,3.502001e+08,9434.863105,100006.000000
max,18.000000,2025.000000,4.165165e+07,8.108467e+06,1.960106e+06,951833.000000,25.188440,5.349173,2.521887,34781.000000,...,4022.863872,2.611006e+11,8253.426439,1.781263e+11,6002.378298,8.589515e+08,20768.288053,5.585059e+08,13569.471504,115026.000000

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
province_id,730.0,1.147260e+01,4.134560e+00,5.000000e+00,8.000000e+00,1.150000e+01,1.500000e+01,1.800000e+01
data_year,730.0,1.998959e+03,1.570426e+01,1.971000e+03,1.986000e+03,1.999000e+03,2.012000e+03,2.025000e+03
population,730.0,4.582358e+06,8.230669e+06,1.899100e+04,5.122542e+05,1.005448e+06,4.510503e+06,4.165165e+07
population_65_plus,730.0,6.084462e+05,1.194007e+06,4.320000e+02,3.599150e+04,1.439500e+05,5.727842e+05,8.108467e+06
population_80_plus,730.0,1.439184e+05,2.930624e+05,5.700000e+01,7.295250e+03,3.458550e+04,1.270595e+05,1.960106e+06
...,...,...,...,...,...,...,...,...
territorial_government_health_expenditure_current,113.0,2.774720e+08,2.109516e+08,6.171500e+06,1.038470e+08,2.245636e+08,4.119098e+08,8.589515e+08
territorial_government_health_expenditure_per_capita,113.0,6.949850e+03,4.934027e+03,2.817007e+02,3.213430e+03,5.908401e+03,1.010084e+04,2.076829e+04
territorial_government_health_expenditure_constant_2010,113.0,2.598165e+08,1.423148e+08,2.782801e+07,1.305288e+08,2.815050e+08,3.502001e+08,5.585059e+08
territorial_government_health_expenditure_constant_2010_per_cap,113.0,6.597884e+03,3.168863e+03,1.270222e+03,4.302342e+03,6.008303e+03,9.434863e+03,1.356947e+04
nurses_total,33.0,7.133424e+04,3.545226e+04,2.859400e+04,3.156600e+04,9.594800e+04,1.000060e+05,1.150260e+05

In [13]:
df[["province_code", "province_name", "data_year"]].head()

  province_code         province_name  data_year
0            PE  Prince Edward Island       2024
1            AB               Alberta       1975
2            BC      British Columbia       1975
3            BC      British Columbia       2022
4            NB         New Brunswick       2021

In [14]:
df.duplicated(
    subset=["province_code", "data_year"]
).sum()

np.int64(0)

In [15]:
df.isna().sum()

province_id                                                          0
province_code                                                        0
province_name                                                        0
data_year                                                            0
population                                                           0
                                                                  ...
territorial_government_health_expenditure_current                  617
territorial_government_health_expenditure_per_capita               617
territorial_government_health_expenditure_constant_2010            617
territorial_government_health_expenditure_constant_2010_per_cap    617
nurses_total                                                       697
Length: 81, dtype: int64

In [16]:
df.isna().mean().mul(100).sort_values(ascending=False)

current_hospital_beds_total                       98.356164
nurses_total                                      95.479452
registered_psychiatric_nurses                     94.520548
hip_fracture_surgery_risk_adjusted_rate           93.835616
hip_fracture_repair_emergency_inpatient_median    91.643836
                                                    ...
population                                         0.000000
population_65_plus                                 0.000000
population_80_plus                                 0.000000
population_85_plus                                 0.000000
population_65_share_pct                            0.000000
Length: 81, dtype: float64

In [17]:
df["province_code"].unique().tolist()

['PE',
 'AB',
 'BC',
 'NB',
 'CA',
 'MB',
 'ON',
 'QC',
 'SK',
 'NS',
 'YT',
 'NL',
 'NT',
 'NU']

In [18]:
df[
    [
        "province_code", "province_name"
    ]
].drop_duplicates().sort_values("province_code")

   province_code              province_name
1             AB                    Alberta
2             BC           British Columbia
5             CA                     Canada
6             MB                   Manitoba
4             NB              New Brunswick
29            NL  Newfoundland and Labrador
14            NS                Nova Scotia
38            NT      Northwest Territories
60            NU                    Nunavut
7             ON                    Ontario
0             PE       Prince Edward Island
8             QC                     Quebec
12            SK               Saskatchewan
15            YT                      Yukon

In [19]:
df["data_year"].min(), df["data_year"].max()

(np.int64(1971), np.int64(2025))

In [20]:
df.groupby("data_year")["province_code"].nunique()

data_year
1971    12
1972    12
1973    12
1974    12
1975    12
1976    12
1977    12
1978    12
1979    12
1980    12
1981    12
1982    12
1983    12
1984    12
1985    12
1986    12
1987    12
1988    12
1989    12
1990    12
1991    14
1992    14
1993    14
1994    14
1995    14
1996    14
1997    14
1998    14
1999    14
2000    14
2001    14
2002    14
2003    14
2004    14
2005    14
2006    14
2007    14
2008    14
2009    14
2010    14
2011    14
2012    14
2013    14
2014    14
2015    14
2016    14
2017    14
2018    14
2019    14
2020    14
2021    14
2022    14
2023    14
2024    14
2025    14
Name: province_code, dtype: int64

In [21]:
df.groupby(
    ["province_code", "province_name"]
)["data_year"].agg(["min", "max", "count"])

                                          min   max  count
province_code province_name
AB            Alberta                    1971  2025     55
BC            British Columbia           1971  2025     55
CA            Canada                     1971  2025     55
MB            Manitoba                   1971  2025     55
NB            New Brunswick              1971  2025     55
NL            Newfoundland and Labrador  1971  2025     55
NS            Nova Scotia                1971  2025     55
NT            Northwest Territories      1991  2025     35
NU            Nunavut                    1991  2025     35
ON            Ontario                    1971  2025     55
PE            Prince Edward Island       1971  2025     55
QC            Quebec                     1971  2025     55
SK            Saskatchewan               1971  2025     55
YT            Yukon                      1971  2025     55

In [22]:
df[
    [
        "population",
        "population_65_plus",
        "population_80_plus",
        "population_85_plus"
    ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
population,730.0,4.582358e+06,8.230669e+06,18991.0,512254.25,1005447.5,4510503.00,41651653.0
population_65_plus,730.0,6.084462e+05,1.194007e+06,432.0,35991.50,143950.0,572784.25,8108467.0
population_80_plus,730.0,1.439184e+05,2.930624e+05,57.0,7295.25,34585.5,127059.50,1960106.0
population_85_plus,730.0,6.707748e+04,1.413021e+05,15.0,3327.50,16144.0,55835.00,951833.0

In [23]:
df[
    [
        "hospital_beds_total",
        "physicians_total",
        "registered_nurses",
        "licensed_practical_nurses",
        "nurse_practitioners",
        "registered_psychiatric_nurses"
    ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
hospital_beds_total,178.0,7137.202247,9259.679899,49.0,488.00,3127.0,11041.25,34781.0
physicians_total,336.0,10996.571429,20442.044501,7.0,265.00,2131.5,11199.00,99555.0
registered_nurses,101.0,27528.792079,31548.140058,392.0,5932.00,10538.0,35516.00,106523.0
licensed_practical_nurses,109.0,10550.128440,13824.277069,105.0,2339.00,3541.0,13239.00,53462.0
nurse_practitioners,102.0,598.313725,987.818318,4.0,141.50,227.0,504.75,4493.0
registered_psychiatric_nurses,40.0,1473.750000,825.591404,679.0,913.75,1176.5,1679.25,3332.0

In [24]:
df[
    [
    "total_health_expenditure_current",
    "total_health_expenditure_per_capita",
    "total_health_expenditure_constant_2010",
    "total_health_expenditure_constant_2010_per_capita",
    "public_health_expenditure_current",
    "public_health_expenditure_per_capita",
    "public_health_expenditure_constant_2010",
    "public_health_expenditure_constant_2010_per_capita",
    "private_health_expenditure_current",
    "private_health_expenditure_per_capita",
    "private_health_expenditure_constant_2010",
    "private_health_expenditure_constant_2010_per_capita",
    "provincial_government_health_expenditure_current",
    "provincial_government_health_expenditure_per_capita",
    "provincial_government_health_expenditure_constant_2010",
    "provincial_government_health_expenditure_constant_2010_per_capi",
    "territorial_government_health_expenditure_current",
    "territorial_government_health_expenditure_per_capita",
    "territorial_government_health_expenditure_constant_2010",
    "territorial_government_health_expenditure_constant_2010_per_cap"
    ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
total_health_expenditure_current,674.0,2.071982e+10,4.886122e+10,1.591580e+07,8.132767e+08,3.835900e+09,1.544169e+10,3.987571e+11
total_health_expenditure_per_capita,674.0,5.051491e+03,4.472296e+03,4.098621e+02,1.899825e+03,3.883709e+03,6.879671e+03,3.008594e+04
total_health_expenditure_constant_2010,674.0,2.226382e+10,4.407259e+10,6.675622e+07,1.360026e+09,4.596623e+09,2.234538e+10,2.831361e+11
total_health_expenditure_constant_2010_per_capita,674.0,5.408806e+03,2.975437e+03,1.962851e+03,3.369040e+03,4.685838e+03,6.454425e+03,1.982099e+04
public_health_expenditure_current,674.0,1.478567e+10,3.469175e+10,1.240050e+07,6.427581e+08,2.922900e+09,1.166065e+10,2.837976e+11
public_health_expenditure_per_capita,674.0,3.911526e+03,3.851973e+03,3.172928e+02,1.475614e+03,2.808750e+03,5.111323e+03,2.805161e+04
public_health_expenditure_constant_2010,674.0,1.587090e+10,3.085592e+10,5.193205e+07,9.341037e+08,3.373674e+09,1.677195e+10,1.935511e+11
public_health_expenditure_constant_2010_per_capita,674.0,4.152953e+03,2.628532e+03,1.472111e+03,2.580572e+03,3.461947e+03,4.611725e+03,1.816118e+04
private_health_expenditure_current,674.0,5.934152e+09,1.420715e+10,3.515300e+06,1.786936e+08,9.066551e+08,3.876805e+09,1.149594e+11
private_health_expenditure_per_capita,674.0,1.139965e+03,8.440801e+02,9.256934e+01,4.150107e+02,9.052598e+02,1.742001e+03,4.822741e+03
private_health_expenditure_constant_2010,674.0,6.392918e+09,1.328778e+10,7.403682e+06,3.039889e+08,1.263095e+09,6.112171e+09,8.958496e+10
private_health_expenditure_constant_2010_per_capita,674.0,1.255854e+03,6.178370e+02,2.648239e+02,7.468369e+02,1.106593e+03,1.720562e+03,4.022864e+03
provincial_government_health_expenditure_current,561.0,1.626805e+10,3.419610e+10,4.150800e+07,1.228779e+09,3.904789e+09,1.507927e+10,2.611006e+11
provincial_government_health_expenditure_per_capita,561.0,2.706749e+03,1.832554e+03,3.008679e+02,1.233451e+03,2.083390e+03,4.190412e+03,8.253426e+03
provincial_government_health_expenditure_constant_2010,561.0,1.752487e+10,3.025923e+10,1.927551e+08,2.136289e+09,4.579779e+09,1.801105e+10,1.781263e+11
provincial_government_health_expenditure_constant_2010_per_capi,561.0,3.069245e+03,9.390566e+02,1.425531e+03,2.319925e+03,2.892217e+03,3.840663e+03,6.002378e+03
territorial_government_health_expenditure_current,113.0,2.774720e+08,2.109516e+08,6.171500e+06,1.038470e+08,2.245636e+08,4.119098e+08,8.589515e+08
territorial_government_health_expenditure_per_capita,113.0,6.949850e+03,4.934027e+03,2.817007e+02,3.213430e+03,5.908401e+03,1.010084e+04,2.076829e+04
territorial_government_health_expenditure_constant_2010,113.0,2.598165e+08,1.423148e+08,2.782801e+07,1.305288e+08,2.815050e+08,3.502001e+08,5.585059e+08
territorial_government_health_expenditure_constant_2010_per_cap,113.0,6.597884e+03,3.168863e+03,1.270222e+03,4.302342e+03,6.008303e+03,9.434863e+03,1.356947e+04

In [25]:
df[
    [
    "hospital_readmission_risk_adjusted_rate",
    "avoidable_hospitalizations_age_standardized_rate",
    "standardized_hospitalization_rate",
    "hip_fracture_surgery_risk_adjusted_rate",
    "joint_replacement_pct_within_benchmark"
    ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
hospital_readmission_risk_adjusted_rate,63.0,9.350794,0.979281,7.800000,8.6000,9.100,9.85,12.40
avoidable_hospitalizations_age_standardized_rate,145.0,426.786207,143.712444,230.000000,333.0000,381.000,494.00,983.00
standardized_hospitalization_rate,402.0,101.286059,27.490568,62.523178,79.2125,95.035,116.96,211.15
hip_fracture_surgery_risk_adjusted_rate,45.0,81.917778,4.632459,70.900000,79.4000,81.700,85.20,90.80
joint_replacement_pct_within_benchmark,77.0,72.090909,18.654181,28.000000,58.0000,73.000,89.00,100.00

In [26]:
df[
   [
    "bladder_cancer_surgery_median",
    "bladder_cancer_surgery_90th_percentile",
    "breast_cancer_surgery_median",
    "breast_cancer_surgery_90th_percentile",
    "cabg_median",
    "cabg_90th_percentile",
    "cataract_surgery_median",
    "cataract_surgery_90th_percentile",
    "colorectal_cancer_surgery_median",
    "colorectal_cancer_surgery_90th_percentile",
    "ct_scan_median",
    "ct_scan_90th_percentile",
    "hip_fracture_repair_median",
    "hip_fracture_repair_90th_percentile",
    "hip_fracture_repair_emergency_inpatient_median",
    "hip_fracture_repair_emergency_inpatient_90th_percentile",
    "hip_replacement_median",
    "hip_replacement_90th_percentile",
    "knee_replacement_median",
    "knee_replacement_90th_percentile",
    "lung_cancer_surgery_median",
    "lung_cancer_surgery_90th_percentile",
    "mri_scan_median",
    "mri_scan_90th_percentile",
    "prostate_cancer_surgery_median",
    "prostate_cancer_surgery_90th_percentile",
    "radiation_therapy_median",
    "radiation_therapy_90th_percentile"
   ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
bladder_cancer_surgery_median,131.0,26.134274,5.742186,15.000000,23.000000,26.000000,29.000000,50.0
bladder_cancer_surgery_90th_percentile,131.0,64.492652,24.198672,26.000000,54.000000,62.000000,70.000000,189.0
breast_cancer_surgery_median,142.0,19.888585,3.912939,8.000000,17.000000,19.276866,22.000000,32.0
breast_cancer_surgery_90th_percentile,142.0,42.831704,9.236446,24.000000,36.000000,42.008941,48.000000,75.8
cabg_median,157.0,8.783727,6.194588,3.000000,6.000000,8.000000,9.000000,63.0
cabg_90th_percentile,157.0,84.473651,47.107996,13.000000,54.000000,75.000000,109.000000,275.0
cataract_surgery_median,194.0,82.136763,45.354828,25.000000,55.000000,71.471771,92.000000,352.6
cataract_surgery_90th_percentile,194.0,234.438648,99.985714,92.000000,160.239241,220.000000,269.345203,666.4
colorectal_cancer_surgery_median,131.0,20.785527,4.040603,12.000000,18.165637,21.000000,23.000000,34.0
colorectal_cancer_surgery_90th_percentile,131.0,47.482050,9.983673,26.000000,41.000000,47.000000,54.500000,73.0
ct_scan_median,116.0,20.697562,11.215512,6.000000,12.531297,20.000000,27.000000,60.0
ct_scan_90th_percentile,116.0,93.971030,58.646556,28.000000,45.750000,82.656468,118.351952,369.3
hip_fracture_repair_median,167.0,23.306138,4.158375,11.641667,20.466667,23.000000,25.000000,41.0
hip_fracture_repair_90th_percentile,167.0,59.455409,10.042720,26.433333,52.187500,59.766667,66.000000,93.0
hip_fracture_repair_emergency_inpatient_median,61.0,26.225601,4.560207,15.600000,23.000000,27.000000,29.766667,35.9
hip_fracture_repair_emergency_inpatient_90th_percentile,61.0,57.300383,10.165278,38.000000,49.000000,58.666667,65.483333,79.0
hip_replacement_median,194.0,175.139046,94.605898,56.000000,98.390767,157.500000,228.875000,502.0
hip_replacement_90th_percentile,194.0,402.198533,172.459504,141.000000,252.750000,356.250000,519.750000,877.0
knee_replacement_median,194.0,222.153804,126.532977,67.000000,126.000000,183.500000,295.000000,648.5
knee_replacement_90th_percentile,194.0,464.871905,202.964956,142.000000,308.250000,409.000000,603.250000,1238.0
lung_cancer_surgery_median,125.0,24.510595,7.175812,7.000000,20.000000,23.000000,27.000000,47.0
lung_cancer_surgery_90th_percentile,125.0,55.656587,16.118452,20.000000,46.712590,55.000000,65.000000,115.0
mri_scan_median,116.0,57.413124,24.682754,23.000000,40.000000,51.000000,71.250000,151.0
mri_scan_90th_percentile,116.0,199.004138,87.455767,60.000000,140.774686,189.000000,232.250000,652.0
prostate_cancer_surgery_median,120.0,46.954482,19.289838,20.000000,37.000000,42.000000,49.866628,157.0
prostate_cancer_surgery_90th_percentile,120.0,108.289519,35.723226,49.000000,84.159470,98.500000,125.000000,239.0
radiation_therapy_median,170.0,10.725570,4.150390,4.000000,7.000000,10.000000,13.000000,27.0
radiation_therapy_90th_percentile,168.0,23.988398,6.797555,14.000000,20.000000,22.147993,27.000000,55.0

<table width="100%">
<tr>
<td width="50%" align="left"></td>
<td width="50%" align="right"><a href="./01_RQ1_population_demand.ipynb">Next: RQ1 — Population Demand →</a></td>
</tr>
</table>